sudo: false

language: php

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

install:
  - composer install

before_script:
  - composer update $PREFER_LOWEST

script:
  - vendor/bin/phpunit
