sudo: false

language: php

matrix:
    include:
        - php: 7.1
        - php: 7.0
        - php: nightly
    allow_failures:
        - php: nightly
    fast_finish: true

install:
    - composer install

script:
    - vendor/bin/phpunit --verbose
    - vendor/bin/behat --verbose
